#
# Notes:
# 
settings:
  arena: 
    minplayers: '3'
    maxplayers: '6'
    lobbylocationx: '0'
    lobbylocationy: '100'
    lobbylocationz: '0'
    starttime: '40'
    timelimit: '600'
    gamelocationx: '0'
    gamelocationy: '100'
    gamelocationz: '0'
    applelocationx: '0'
    applelocationy: '100'
    applelocationz: '0'
    